site_name: moai

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
        default_handler: python
        handlers:
            python:
                selection:
                    members: true
                rendering:
                    show_source: false
                    show_if_no_docstring: false
                    heading_level: 3
                    show_root_heading: false
                    show_root_toc_entry: false
                    show_root_full_path: false
                    show_object_full_path: false
                    show_category_heading: false
                    group_by_category: false
        watch:
            - moai            
  
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      
extra_javascript:
  - javascripts/config.js
  - javascripts/keywords.js
  - javascripts/datatabs.js #NOTE: update mkdocstrings and check if issue is fixed
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js  
  
extra_css:
  - stylesheets/keywords.css
  - stylesheets/extra.css
  - stylesheets/mkdocstrings.css
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css

nav:
  - Introduction: index.md
